site_accounts/urls.py
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('sites/', include('dj_site_accounts.sites_profiles.urls')),

    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

dj_site_accounts/authentication/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from dj_site_accounts.common.utils import get_settings_value


class HasPhone(models.Model):
    class Meta:
        abstract = True

    phone = PhoneNumberField(unique=True,
                             error_messages={'unique': _("A user with that phone already exists.")})

    phone_verified_at = models.DateTimeField(blank=True, null=True)

    def verify_phone(self):
        self.phone_verified_at = now()
        self.save()


class HasOTPVerification(HasPhone):
    class Meta:
        abstract = True

    key = models.CharField(max_length=100, unique=True, blank=True)

    if get_settings_value('OTP_VERIFICATION_TYPE') == 'HOTP':
        otp_counter = models.IntegerField(default=0)

dj_site_accounts/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate, password_validation
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from translation.forms import TranslatableModelForm

from .models import SiteProfile
from .templatetags.auth import get_authentication_field_placeholder
from .verify_phone import VerifyPhone

UserModel = get_user_model()


class MultipleLoginForm(forms.ModelForm):
    identifier = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            "placeholder": get_authentication_field_placeholder(),
            "class": "form-control bg-transparent"
        }))
    password = forms.CharField(
        label=_("Password"),
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}))
    remember_me = forms.BooleanField(
        required=False,
        label=_('Remember Me'),
        initial=False)

    error_messages = {
        'required': _("This field is required"),
        'invalid_login': _(
            "Please enter a correct credentials. Note that "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
        "invalid_credentials": _("Please enter a correct credentials"),
    }

    class Meta:
        model = UserModel
        fields = ('identifier', 'password', 'remember_me')

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(MultipleLoginForm, self).__init__(*args, **kwargs)

    def get_user(self):
        return self.user_cache

    def clean(self):
        identifier = self.cleaned_data.get('identifier', None)
        password = self.cleaned_data.get('password', None)
        remember_me = self.cleaned_data.get('remember_me')

        if not identifier or not password:
            if not identifier:
                self.add_error('identifier', ValidationError(self.error_messages['required'], code='required'))

            if not password:
                self.add_error('password', ValidationError(self.error_messages['required'], code='required'))
        else:
            credentials = {"password": password, 'identifier': identifier}

            self.user_cache = authenticate(request=self.request, **credentials)
            if not self.user_cache:
                raise ValidationError(self.error_messages['invalid_login'], code='invalid_login')
            if not remember_me and self.request:
                self.request.session.set_expiry(0)
                self.request.session.modified = True
            else:
                if not self.user_cache.is_active:
                    raise ValidationError(self.error_messages['inactive'], code='inactive')

        return self.cleaned_data


class UserCreationForm(BaseUserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'off',
            "placeholder": _("Password"),
            "class": "form-control bg-transparent"
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'off',
            "placeholder": _("Password Confirmation"),
            "class": "form-control bg-transparent"
        }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    toc = forms.BooleanField(
        required=True,
        label=_('terms'),
        initial=False)

    class Meta(BaseUserCreationForm.Meta):
        model = UserModel
        widgets = {
            "password2": forms.PasswordInput(attrs={
                'autocomplete': 'off',
                "placeholder": _("Password Confirmation"),
                "class": "form-control bg-transparent"
            })
        }

    def is_valid(self):
        result = super().is_valid()
        # loop on *all* fields if key '__all__' found else only on errors:
        for x in (self.fields if '__all__' in self.errors else self.errors):
            attrs = self.fields[x].widget.attrs
            attrs.update({'class': attrs.get('class', '') + ' is-invalid'})
        return result


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your username"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Username"),
            "class": "form-control bg-transparent"
        }))

    first_name = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your first name"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("First Name"),
            "class": "form-control bg-transparent"
        }))

    last_name = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your last name"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Last Name"),
            "class": "form-control bg-transparent"
        }))

    email = forms.EmailField(
        required=True,
        max_length=100, help_text=_("Required, please provide your email"),
        widget=forms.EmailInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Email"),
            "class": "form-control bg-transparent"
        }))

    phone = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your phone number"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Phone"),
            "class": "form-control bg-transparent"
        }))

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("username", "first_name", "last_name", 'email', 'phone',)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if UserModel.objects.filter(phone=phone).exists():
            raise ValidationError("Phone already exists", code="unique")
        return phone

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserModel.objects.filter(email=email).exists():
            raise ValidationError("Email already exists", code="unique")
        return email


class VerifyPhoneForm(forms.Form):
    code = forms.CharField(max_length=6, min_length=6)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(VerifyPhoneForm, self).__init__(*args, **kwargs)

    def clean(self):
        code = self.cleaned_data.get('code')

        success = VerifyPhone(self.user, self.user.phone).check(code)
        if not success:
            self.add_error('code', ValidationError(_("The provided code is invalid"), code='invalid_code'))

        return self.cleaned_data


class SiteProfileForm(TranslatableModelForm):
    domain = forms.URLField(
        required=True,
        initial="",
        widget=forms.TextInput(attrs={
            "class": "form-control bg-transparent",
            "placeholder": _("Domain")
        }))

    class Meta:
        model = SiteProfile
        fields = ('domain', 'site', 'name', 'description', 'address', 'copyrights', 'keywords', 'logo')
        widgets = {
            "site": forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(SiteProfileForm, self).__init__(*args, **kwargs)
        self.fields['site'].required = False
        self.fields['keywords'].required = False
        self.fields['copyrights'].required = False
        self.fields['address'].required = False
        self.fields['description'].required = False
        if self.instance.pk:
            self.fields['domain'].initial = self.instance.site.domain

    def save(self, commit=True):
        domain = self.cleaned_data.pop('domain')
        domain = domain.split('://')[1]
        instance = super().save(commit=False)
        if commit:
            site = self.cleaned_data.get('site', None)
            if not site:
                site = Site.objects.create(
                    domain=domain,
                    name=self.cleaned_data.get('name'))
                instance = site.siteprofile
            else:
                site.name = self.cleaned_data.get('name')
                site.domain = domain
                site.save()
            instance.save()
        return instance

dj_site_accounts/authentication/views/site.py
from django.contrib.auth.views import LoginView as BaseLoginView

from authentication.mixins import LoginGetFormClassMixin
from common.utils import get_settings_value


class LoginView(LoginGetFormClassMixin, BaseLoginView):
    redirect_authenticated_user = True

    def get_template_names(self):
        """
        returns the template based on selected theme in settings
        """
        return ['dj_site_accounts/authentication/themes/{}/login.html'.format(
            get_settings_value('AUTHENTICATION_THEME', 'corporate'))]

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/_form_errors.html
{% load i18n %}
{% if form.non_field_errors %}
  <div class="alert alert-danger d-flex align-items-center p-5">
    <span class="svg-icon svg-icon-2hx svg-icon-danger me-3">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path opacity="0.3"
              d="M20.5543 4.37824L12.1798 2.02473C12.0626 1.99176 11.9376 1.99176 11.8203 2.02473L3.44572 4.37824C3.18118 4.45258 3 4.6807 3 4.93945V13.569C3 14.6914 3.48509 15.8404 4.4417 16.984C5.17231 17.8575 6.18314 18.7345 7.446 19.5909C9.56752 21.0295 11.6566 21.912 11.7445 21.9488C11.8258 21.9829 11.9129 22 12.0001 22C12.0872 22 12.1744 21.983 12.2557 21.9488C12.3435 21.912 14.4326 21.0295 16.5541 19.5909C17.8169 18.7345 18.8277 17.8575 19.5584 16.984C20.515 15.8404 21 14.6914 21 13.569V4.93945C21 4.6807 20.8189 4.45258 20.5543 4.37824Z"
              fill="currentColor"></path>
        <path
            d="M14.854 11.321C14.7568 11.2282 14.6388 11.1818 14.4998 11.1818H14.3333V10.2272C14.3333 9.61741 14.1041 9.09378 13.6458 8.65628C13.1875 8.21876 12.639 8 12 8C11.361 8 10.8124 8.21876 10.3541 8.65626C9.89574 9.09378 9.66663 9.61739 9.66663 10.2272V11.1818H9.49999C9.36115 11.1818 9.24306 11.2282 9.14583 11.321C9.0486 11.4138 9 11.5265 9 11.6591V14.5227C9 14.6553 9.04862 14.768 9.14583 14.8609C9.24306 14.9536 9.36115 15 9.49999 15H14.5C14.6389 15 14.7569 14.9536 14.8542 14.8609C14.9513 14.768 15 14.6553 15 14.5227V11.6591C15.0001 11.5265 14.9513 11.4138 14.854 11.321ZM13.3333 11.1818H10.6666V10.2272C10.6666 9.87594 10.7969 9.57597 11.0573 9.32743C11.3177 9.07886 11.6319 8.9546 12 8.9546C12.3681 8.9546 12.6823 9.07884 12.9427 9.32743C13.2031 9.57595 13.3333 9.87594 13.3333 10.2272V11.1818Z"
            fill="currentColor"></path>
      </svg>
    </span>
    <div class="d-flex flex-column">
      <h4 class="mb-1 text-dark">{% trans "Alert" %}</h4>
      {% for value in form.non_field_errors %}
        <span>{{ value }}</span>
      {% endfor %}

    </div>
  </div>
{% endif %}

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/_head.html
{% load static %}
<head>
  <title>Metronic - the world's #1 selling Bootstrap Admin Theme Ecosystem for HTML, Vue, React, Angular & Laravel by
    Keenthemes</title>
  <meta charset="utf-8"/>
  <meta name="description"
        content="The most advanced Bootstrap Admin Theme on Themeforest trusted by 100,000 beginners and professionals. Multi-demo, Dark Mode, RTL support and complete React, Angular, Vue, Asp.Net Core, Blazor, Django, Flask & Laravel versions. Grab your copy now and get life-time updates for free."/>
  <meta name="keywords"
        content="metronic, bootstrap, bootstrap 5, angular, VueJs, React, Asp.Net Core, Blazor, Django, Flask & Laravel starter kits, admin themes, web design, figma, web development, free templates, free admin themes, bootstrap theme, bootstrap template, bootstrap dashboard, bootstrap dak mode, bootstrap button, bootstrap datepicker, bootstrap timepicker, fullcalendar, datatables, flaticon"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta property="og:locale" content="en_US"/>
  <meta property="og:type" content="article"/>
  <meta property="og:title"
        content="Metronic | Bootstrap HTML, VueJS, React, Angular, Asp.Net Core, Blazor, Django, Flask & Laravel Admin Dashboard Theme"/>
  <meta property="og:url" content="https://keenthemes.com/metronic"/>
  <meta property="og:site_name" content="Keenthemes | Metronic"/>

  <link rel="canonical" href="https://preview.keenthemes.com/metronic8"/>
  <link rel="shortcut icon" href="assets/media/logos/favicon.ico"/>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700"/>

  {% if LANGUAGE_BIDI %}
    <link href="{% static "dj_accounts/plugins/global/plugins.bundle.rtl.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "dj_accounts/css/style.bundle.rtl.css" %}" rel="stylesheet" type="text/css"/>
  {% else %}
    <link href="{% static "dj_accounts/plugins/global/plugins.bundle.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "dj_accounts/css/style.bundle.css" %}" rel="stylesheet" type="text/css"/>
  {% endif %}
</head>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/_page_header.html
{% load i18n %}
<div class="text-center mb-11">
  <h1 class="text-dark fw-bolder mb-3">{{ title }}</h1>
  {% if has_social_auth %}
    <div class="text-gray-500 fw-semibold fs-6">{% trans "Using Social Media Account" %}</div>
  {% endif %}
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/_phone_verification.html
{% load static i18n %}
<form class="form w-100 mb-13"
      method="post"
    {% if phone_id %}
      action="{% url "verify-phone-by-id" phone_id %}"
    {% else %}
      action="{% url "verify-phone" %}"
    {% endif %}>
  {% csrf_token %}
  <input type="hidden" id="id_code" name="code">
  <div class="text-center mb-10">
    <img alt="Logo" class="mh-125px" src="{% static "dj_accounts/images/smartphone-2.svg" %}"/>
  </div>
  <div class="text-center mb-10">
    <h1 class="text-dark mb-3">{% trans "Verify your phone" %}</h1>
    <div class="text-muted fw-semibold fs-5 mb-5">{% trans "Enter the verification code we sent to" %}</div>
    <div class="fw-bold text-dark fs-3" dir="ltr">{{ hashed_phone }}</div>
  </div>
  <div class="mb-10">
    <div class="fw-bold text-start text-dark fs-6 mb-1 ms-1">
      {% blocktrans with length=otp_length %}Type your {{ length }} digit security code {% endblocktrans %}
    </div>
    <div class="d-flex flex-wrap flex-stack" dir="ltr">
      {% for i in otp_range %}
        <input data-otp-input="{{ i }}"
               type="text"
               data-inputmask="'mask': '9', 'placeholder': ''"
               maxlength="1"
               class="form-control bg-transparent h-60px w-60px fs-2qx text-center mx-1 my-2" value=""/>
      {% endfor %}
    </div>
  </div>
  <div class="d-flex flex-center">
    <button type="submit" id="form-submit" class="btn btn-lg btn-primary fw-bold disabled">
      {% trans "Submit" %}
    </button>
  </div>
</form>
<div class="text-center fw-semibold fs-5"
     data-otp-expires-at="{{ otp_expiry }}"
     data-resend-url="{% url "resend_phone_activation" %}"></div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/_scripts.html
{% load static %}

<script>var hostUrl = "assets/";</script>

<script src="{% static "dj_accounts/plugins/global/plugins.bundle.js" %}"></script>
<script src="{% static "dj_accounts/js/scripts.bundle.js" %}"></script>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/_theme.html
<script>var defaultThemeMode = "light";
var themeMode;
if (document.documentElement) {
  if (document.documentElement.hasAttribute("data-theme-mode")) {
    themeMode = document.documentElement.getAttribute("data-theme-mode");
  } else {
    if (localStorage.getItem("data-theme") !== null) {
      themeMode = localStorage.getItem("data-theme");
    } else {
      themeMode = defaultThemeMode;
    }
  }
  if (themeMode === "system") {
    themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  }
  document.documentElement.setAttribute("data-theme", themeMode);
}</script>