site_accounts/urls.py
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('sites/', include('dj_site_accounts.sites_profiles.urls')),

    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

dj_site_accounts/authentication/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from dj_site_accounts.common.utils import get_settings_value


class HasPhone(models.Model):
    class Meta:
        abstract = True

    phone = PhoneNumberField(unique=True,
                             error_messages={'unique': _("A user with that phone already exists.")})

    phone_verified_at = models.DateTimeField(blank=True, null=True)

    def verify_phone(self):
        self.phone_verified_at = now()
        self.save()


class HasOTPVerification(HasPhone):
    class Meta:
        abstract = True

    key = models.CharField(max_length=100, unique=True, blank=True)

    if get_settings_value('OTP_VERIFICATION_TYPE') == 'HOTP':
        otp_counter = models.IntegerField(default=0)

dj_site_accounts/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate, password_validation
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from translation.forms import TranslatableModelForm

from .models import SiteProfile
from .templatetags.auth import get_authentication_field_placeholder
from .verify_phone import VerifyPhone

UserModel = get_user_model()


class MultipleLoginForm(forms.ModelForm):
    identifier = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            "placeholder": get_authentication_field_placeholder(),
            "class": "form-control bg-transparent"
        }))
    password = forms.CharField(
        label=_("Password"),
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}))
    remember_me = forms.BooleanField(
        required=False,
        label=_('Remember Me'),
        initial=False)

    error_messages = {
        'required': _("This field is required"),
        'invalid_login': _(
            "Please enter a correct credentials. Note that "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
        "invalid_credentials": _("Please enter a correct credentials"),
    }

    class Meta:
        model = UserModel
        fields = ('identifier', 'password', 'remember_me')

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(MultipleLoginForm, self).__init__(*args, **kwargs)

    def get_user(self):
        return self.user_cache

    def clean(self):
        identifier = self.cleaned_data.get('identifier', None)
        password = self.cleaned_data.get('password', None)
        remember_me = self.cleaned_data.get('remember_me')

        if not identifier or not password:
            if not identifier:
                self.add_error('identifier', ValidationError(self.error_messages['required'], code='required'))

            if not password:
                self.add_error('password', ValidationError(self.error_messages['required'], code='required'))
        else:
            credentials = {"password": password, 'identifier': identifier}

            self.user_cache = authenticate(request=self.request, **credentials)
            if not self.user_cache:
                raise ValidationError(self.error_messages['invalid_login'], code='invalid_login')
            if not remember_me and self.request:
                self.request.session.set_expiry(0)
                self.request.session.modified = True
            else:
                if not self.user_cache.is_active:
                    raise ValidationError(self.error_messages['inactive'], code='inactive')

        return self.cleaned_data


class UserCreationForm(BaseUserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'off',
            "placeholder": _("Password"),
            "class": "form-control bg-transparent"
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'off',
            "placeholder": _("Password Confirmation"),
            "class": "form-control bg-transparent"
        }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    toc = forms.BooleanField(
        required=True,
        label=_('terms'),
        initial=False)

    class Meta(BaseUserCreationForm.Meta):
        model = UserModel
        widgets = {
            "password2": forms.PasswordInput(attrs={
                'autocomplete': 'off',
                "placeholder": _("Password Confirmation"),
                "class": "form-control bg-transparent"
            })
        }

    def is_valid(self):
        result = super().is_valid()
        # loop on *all* fields if key '__all__' found else only on errors:
        for x in (self.fields if '__all__' in self.errors else self.errors):
            attrs = self.fields[x].widget.attrs
            attrs.update({'class': attrs.get('class', '') + ' is-invalid'})
        return result


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your username"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Username"),
            "class": "form-control bg-transparent"
        }))

    first_name = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your first name"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("First Name"),
            "class": "form-control bg-transparent"
        }))

    last_name = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your last name"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Last Name"),
            "class": "form-control bg-transparent"
        }))

    email = forms.EmailField(
        required=True,
        max_length=100, help_text=_("Required, please provide your email"),
        widget=forms.EmailInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Email"),
            "class": "form-control bg-transparent"
        }))

    phone = forms.CharField(
        required=True,
        max_length=100, help_text=_("Required, please provide your phone number"),
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "placeholder": _("Phone"),
            "class": "form-control bg-transparent"
        }))

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("username", "first_name", "last_name", 'email', 'phone',)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if UserModel.objects.filter(phone=phone).exists():
            raise ValidationError("Phone already exists", code="unique")
        return phone

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserModel.objects.filter(email=email).exists():
            raise ValidationError("Email already exists", code="unique")
        return email


class VerifyPhoneForm(forms.Form):
    code = forms.CharField(max_length=6, min_length=6)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(VerifyPhoneForm, self).__init__(*args, **kwargs)

    def clean(self):
        code = self.cleaned_data.get('code')

        success = VerifyPhone(self.user, self.user.phone).check(code)
        if not success:
            self.add_error('code', ValidationError(_("The provided code is invalid"), code='invalid_code'))

        return self.cleaned_data


class SiteProfileForm(TranslatableModelForm):
    domain = forms.URLField(
        required=True,
        initial="",
        widget=forms.TextInput(attrs={
            "class": "form-control bg-transparent",
            "placeholder": _("Domain")
        }))

    class Meta:
        model = SiteProfile
        fields = ('domain', 'site', 'name', 'description', 'address', 'copyrights', 'keywords', 'logo')
        widgets = {
            "site": forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(SiteProfileForm, self).__init__(*args, **kwargs)
        self.fields['site'].required = False
        self.fields['keywords'].required = False
        self.fields['copyrights'].required = False
        self.fields['address'].required = False
        self.fields['description'].required = False
        if self.instance.pk:
            self.fields['domain'].initial = self.instance.site.domain

    def save(self, commit=True):
        domain = self.cleaned_data.pop('domain')
        domain = domain.split('://')[1]
        instance = super().save(commit=False)
        if commit:
            site = self.cleaned_data.get('site', None)
            if not site:
                site = Site.objects.create(
                    domain=domain,
                    name=self.cleaned_data.get('name'))
                instance = site.siteprofile
            else:
                site.name = self.cleaned_data.get('name')
                site.domain = domain
                site.save()
            instance.save()
        return instance

dj_site_accounts/authentication/views/site.py
from django.contrib.auth.views import LoginView as BaseLoginView

from authentication.mixins import LoginGetFormClassMixin
from common.utils import get_settings_value


class LoginView(LoginGetFormClassMixin, BaseLoginView):
    redirect_authenticated_user = True

    def get_template_names(self):
        """
        returns the template based on selected theme in settings
        """
        return ['dj_site_accounts/authentication/themes/{}/login.html'.format(
            get_settings_value('AUTHENTICATION_THEME', 'corporate'))]

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_identifier.html
{% load auth %}
<div class="mb-8">
  <label class="sr-only" for="{{ form.identifier.id_for_label }}">{{ form.identifier.label }}</label>

  <input type="text"
         id="{{ form.identifier.id_for_label }}"
         name="{{ form.identifier.html_name }}"
         placeholder="{% get_authentication_field_placeholder %}"
         value="{{ form.identifier.value|default_if_none:'' }}"
         autocomplete="off"
         class="form-control bg-transparent"/>

  {% if form.identifier.errors %}
    <div class="invalid-feedback" id="{{ form.identifier.id_for_label }}-feedback">
      {% for error in field.errors %}
        <div>{{ error }}</div>
      {% endfor %}
    </div>
  {% elif field.help_text %}
    <div class="text-muted mt-1">{{ field.help_text }}</div>
  {% endif %}
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_image_input.html
{% load static %}

{{ field.field.widget.items }}
<div class="image-input image-input-outline"
     data-kt-image-input="true"
     style="background-image: url({% static "dj_accounts/images/icon.svg" %})">
  <div class="image-input-wrapper w-125px h-125px"
      {% if field.value %}
       style="background-image: url({{ field.value.url }})"
      {% endif %}></div>

  <!--begin::Edit button-->
  <label
      class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
      data-kt-image-input-action="change"
      data-bs-toggle="tooltip"
      data-bs-dismiss="click"
      title="Change avatar">
    <span class="svg-icon svg-icon-2">
       <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
              d="M2 4.63158C2 3.1782 3.1782 2 4.63158 2H13.47C14.0155 2 14.278 2.66919 13.8778 3.04006L12.4556 4.35821C11.9009 4.87228 11.1726 5.15789 10.4163 5.15789H7.1579C6.05333 5.15789 5.15789 6.05333 5.15789 7.1579V16.8421C5.15789 17.9467 6.05333 18.8421 7.1579 18.8421H16.8421C17.9467 18.8421 18.8421 17.9467 18.8421 16.8421V13.7518C18.8421 12.927 19.1817 12.1387 19.7809 11.572L20.9878 10.4308C21.3703 10.0691 22 10.3403 22 10.8668V19.3684C22 20.8218 20.8218 22 19.3684 22H4.63158C3.1782 22 2 20.8218 2 19.3684V4.63158Z"
              fill="currentColor"></path>
        <path
            d="M10.9256 11.1882C10.5351 10.7977 10.5351 10.1645 10.9256 9.77397L18.0669 2.6327C18.8479 1.85165 20.1143 1.85165 20.8953 2.6327L21.3665 3.10391C22.1476 3.88496 22.1476 5.15129 21.3665 5.93234L14.2252 13.0736C13.8347 13.4641 13.2016 13.4641 12.811 13.0736L10.9256 11.1882Z"
            fill="currentColor"></path>
        <path
            d="M8.82343 12.0064L8.08852 14.3348C7.8655 15.0414 8.46151 15.7366 9.19388 15.6242L11.8974 15.2092C12.4642 15.1222 12.6916 14.4278 12.2861 14.0223L9.98595 11.7221C9.61452 11.3507 8.98154 11.5055 8.82343 12.0064Z"
            fill="currentColor"></path>
      </svg>
    </span>

    <input type="file" name="{{ field.html_name }}"/>
    <input type="hidden" name="{{ field.html_name }}-clear"/>
  </label>

  <span
      class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
      data-kt-image-input-action="cancel"
      data-bs-toggle="tooltip"
      data-bs-dismiss="click"
      title="Cancel avatar">
    <span class="svg-icon svg-icon-2">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path opacity="0.3"
              d="M6.7 19.4L5.3 18C4.9 17.6 4.9 17 5.3 16.6L16.6 5.3C17 4.9 17.6 4.9 18 5.3L19.4 6.7C19.8 7.1 19.8 7.7 19.4 8.1L8.1 19.4C7.8 19.8 7.1 19.8 6.7 19.4Z"
              fill="currentColor"></path>
        <path
            d="M19.5 18L18.1 19.4C17.7 19.8 17.1 19.8 16.7 19.4L5.40001 8.1C5.00001 7.7 5.00001 7.1 5.40001 6.7L6.80001 5.3C7.20001 4.9 7.80001 4.9 8.20001 5.3L19.5 16.6C19.9 16.9 19.9 17.6 19.5 18Z"
            fill="currentColor"></path>
      </svg>
    </span>
  </span>

  <span
      class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
      data-kt-image-input-action="remove"
      data-bs-toggle="tooltip"
      data-bs-dismiss="click"
      title="Remove avatar">
    <span class="svg-icon svg-icon-2">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z"
            fill="currentColor"></path>
        <path opacity="0.5"
              d="M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z"
              fill="currentColor"></path>
        <path opacity="0.5" d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z"
              fill="currentColor"></path>
        </svg>
      </span>
  </span>
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_input.html
{% load auth %}
<div class="mb-8">
  <label
      for="{{ field.id_for_label }}"
      {% if show_label %}
      class="{% if  field.field.required %}required {% endif %}form-label"
      {% else %}
      class="sr-only"
      {% endif %}>{{ field.label }}</label>

  {{ field }}

  {% if field.errors %}
    <div class="invalid-feedback" id="{{ field.id_for_label }}-feedback">
      {% for error in field.errors %}
        <div>{{ error }}</div>
      {% endfor %}

    </div>
  {% elif field.help_text %}
    <div class="text-muted mt-1">{{ field.help_text }}</div>
  {% endif %}
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_password.html
<div class="fv-row mb-3">
  <label class="sr-only" for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
  <input type="password"
         id="{{ form.password.id_for_label }}"
         name="{{ form.password.html_name }}"
         placeholder="{{ form.password.label }}"
         autocomplete="off"
         class="form-control bg-transparent"/>
  {% if form.password.errors %}
    <div class="invalid-feedback" id="{{ form.password.id_for_label }}-feedback">
      {% for error in field.errors %}
        <div>{{ error }}</div>
      {% endfor %}
    </div>
  {% elif field.help_text %}
    <div class="text-muted mt-1">{{ field.help_text }}</div>
  {% endif %}
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_password_meter.html
<div class="fv-row mb-8" data-kt-password-meter="true">
  <div class="mb-1">

    <div class="position-relative mb-3">
      <label class="sr-only" for="{{ field.id_for_label }}">{{ field.label }}</label>
      <input class="form-control bg-transparent"
             id="{{ field.id_for_label }}"
             type="password"
             placeholder="{{ field.field.widget.attrs.placeholder }}"
             name="{{ field.name }}"
             autocomplete="off"/>
      <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2"
            data-kt-password-meter-control="visibility">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
             class="bi bi-eye-slash fs-2" viewBox="0 0 16 16">
          <path
              d="M13.359 11.238C15.06 9.72 16 8 16 8s-3-5.5-8-5.5a7.028 7.028 0 0 0-2.79.588l.77.771A5.944 5.944 0 0 1 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.134 13.134 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755-.165.165-.337.328-.517.486l.708.709z"></path>
          <path
              d="M11.297 9.176a3.5 3.5 0 0 0-4.474-4.474l.823.823a2.5 2.5 0 0 1 2.829 2.829l.822.822zm-2.943 1.299.822.822a3.5 3.5 0 0 1-4.474-4.474l.823.823a2.5 2.5 0 0 0 2.829 2.829z"></path>
          <path
              d="M3.35 5.47c-.18.16-.353.322-.518.487A13.134 13.134 0 0 0 1.172 8l.195.288c.335.48.83 1.12 1.465 1.755C4.121 11.332 5.881 12.5 8 12.5c.716 0 1.39-.133 2.02-.36l.77.772A7.029 7.029 0 0 1 8 13.5C3 13.5 0 8 0 8s.939-1.721 2.641-3.238l.708.709zm10.296 8.884-12-12 .708-.708 12 12-.708.708z"></path>
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye fs-2 d-none"
             viewBox="0 0 16 16">
          <path
              d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"></path>
          <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"></path>
        </svg>
      </span>
    </div>

    <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
      <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
      <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
      <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
      <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
    </div>
  </div>
    {% if field.errors %}
    <div class="invalid-feedback" id="{{ field.id_for_label }}-feedback">
      {% for error in field.errors %}
        <div>{{ error }}</div>
      {% endfor %}
    </div>
  {% elif field.help_text %}
    <div class="text-muted">{{ field.help_text }}</div>
  {% endif %}
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_remember_me.html
{% load i18n %}
<div class="form-check form-check-custom form-check-solid">
  <input class="form-check-input" type="checkbox" id="id_remember_me" name="remember_me"/>
  <label class="form-check-label" for="id_remember_me">
    {% trans "Remember Me" %}
  </label>
</div>

dj_site_accounts/authentication/templates/dj_site_accounts/authentication/partials/fields/_tems_and_conditions.html
{% load i18n %}
<div class="fv-row mb-8">
  <label class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" name="toc" value="1"/>
    <span class="form-check-label fw-semibold text-gray-700 fs-base ms-1">
      {% trans "I Accept the" %} <a href="#" class="ms-1 link-primary">{% trans "Terms" %}</a>
    </span>
  </label>
</div>